id: qualys-excluded-host-test
version: 2
vcShouldKeepItemLegacyProdMachine: false
name: qualys-excluded-host-test
description: Testing excluded hosts commands
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 570d6969-9dbe-4794-8b0a-5d13fe7b4497
    type: start
    task:
      id: 570d6969-9dbe-4794-8b0a-5d13fe7b4497
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "89"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "20":
    id: "20"
    taskid: 65a33a2b-dae7-4560-869b-7adba3c98252
    type: regular
    task:
      id: 65a33a2b-dae7-4560-869b-7adba3c98252
      version: -1
      name: qualys-host-excluded-list
      description: Show the excluded host list for the user's account. Hosts in your
        excluded host list will not be scanned.
      script: QualysV2|||qualys-host-excluded-list
      type: regular
      iscommand: true
      brand: QualysV2
    nexttasks:
      '#none#':
      - "21"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "21":
    id: "21"
    taskid: a82ef0b6-2eff-4dfe-80d8-1e4a004c4a28
    type: condition
    task:
      id: a82ef0b6-2eff-4dfe-80d8-1e4a004c4a28
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "92"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: Qualys.Excluded.Host.Address
            iscontext: true
      - - operator: isEmpty
          left:
            value:
              simple: Qualys.Excluded.Host.#text
            iscontext: true
      - - operator: isEmpty
          left:
            value:
              simple: Qualys.Excluded.Host.@expiration_date
            iscontext: true
      - - operator: isEmpty
          left:
            value:
              simple: Qualys.Excluded.Host.Range
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "53":
    id: "53"
    taskid: c120bb22-94fb-439e-8bd6-034581a70beb
    type: regular
    task:
      id: c120bb22-94fb-439e-8bd6-034581a70beb
      version: -1
      name: qualys-host-excluded-manage
      description: Manage your excluded IPs list using the Excluded IP. The IPs in
        your excluded IPs list will not be scanned.
      script: QualysV2|||qualys-host-excluded-manage
      type: regular
      iscommand: true
      brand: QualysV2
    nexttasks:
      '#none#':
      - "54"
    scriptarguments:
      action:
        simple: remove_all
      comment:
        simple: remove all
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "54":
    id: "54"
    taskid: 3e4b08d1-a385-4ed4-8660-a81a8859341f
    type: condition
    task:
      id: 3e4b08d1-a385-4ed4-8660-a81a8859341f
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "20"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Qualys.Endpoint.KEY
            iscontext: true
          right:
            value:
              simple: Removed IPs
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "75":
    id: "75"
    taskid: 6b2ecfbd-a550-4951-8208-761ea14b40bf
    type: title
    task:
      id: 6b2ecfbd-a550-4951-8208-761ea14b40bf
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2265
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "89":
    id: "89"
    taskid: 637e496b-9fbc-44d6-89f0-ffbc88fa261c
    type: title
    task:
      id: 637e496b-9fbc-44d6-89f0-ffbc88fa261c
      version: -1
      name: Excluded Host
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "91"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "91":
    id: "91"
    taskid: dfcb5400-31c8-40bf-8462-269d64b801c8
    type: regular
    task:
      id: dfcb5400-31c8-40bf-8462-269d64b801c8
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "53"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "92":
    id: "92"
    taskid: c18bf893-edc3-4a88-8405-e86a69c4a1b3
    type: regular
    task:
      id: c18bf893-edc3-4a88-8405-e86a69c4a1b3
      version: -1
      name: qualys-host-excluded-manage
      description: Manage your excluded IPs list using the Excluded IP. The IPs in
        your excluded IPs list will not be scanned.
      script: QualysV2|||qualys-host-excluded-manage
      type: regular
      iscommand: true
      brand: QualysV2
    nexttasks:
      '#none#':
      - "93"
    scriptarguments:
      action:
        simple: add
      comment:
        simple: add with expiry
      expiry_days:
        simple: "3"
      ips:
        simple: 1.1.1.1
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "93":
    id: "93"
    taskid: 7e035066-6b57-4e01-87e0-7363a992558b
    type: condition
    task:
      id: 7e035066-6b57-4e01-87e0-7363a992558b
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "94"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Qualys.Endpoint.[1].VALUE
            iscontext: true
          right:
            value:
              simple: 1.1.1.1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "94":
    id: "94"
    taskid: 19e6d521-8dd1-4ace-818d-a6fe75dbed75
    type: regular
    task:
      id: 19e6d521-8dd1-4ace-818d-a6fe75dbed75
      version: -1
      name: qualys-host-excluded-list
      description: Show the excluded host list for the user's account. Hosts in your
        excluded host list will not be scanned.
      script: QualysV2|||qualys-host-excluded-list
      type: regular
      iscommand: true
      brand: QualysV2
    nexttasks:
      '#none#':
      - "95"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "95":
    id: "95"
    taskid: 94c9afc2-1975-402d-8b76-196b465eeeff
    type: condition
    task:
      id: 94c9afc2-1975-402d-8b76-196b465eeeff
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "96"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Qualys.Excluded.Host.Address.#text
            iscontext: true
          right:
            value:
              simple: 1.1.1.1
      - - operator: isNotEmpty
          left:
            value:
              simple: Qualys.Excluded.Host.Address.@expiration_date
            iscontext: true
      - - operator: isEmpty
          left:
            value:
              simple: Qualys.Excluded.Host.Range
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "96":
    id: "96"
    taskid: 6a90312a-07a4-4e7d-8f7c-96da0302ca7d
    type: regular
    task:
      id: 6a90312a-07a4-4e7d-8f7c-96da0302ca7d
      version: -1
      name: qualys-host-excluded-manage
      description: Manage your excluded IPs list using the Excluded IP. The IPs in
        your excluded IPs list will not be scanned.
      script: QualysV2|||qualys-host-excluded-manage
      type: regular
      iscommand: true
      brand: QualysV2
    nexttasks:
      '#none#':
      - "75"
    scriptarguments:
      action:
        simple: remove_all
      comment:
        simple: clear list
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1915
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2280,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
sourceplaybookid: QualysVulnerabilityManagement-Test
